version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    ignore:
      - dependency-name: "org.apache.maven.plugins:maven-install-plugin"
        # For Maven Install Plugin, ignore all updates. https://stackoverflow.com/a/55073528
