prefix geoc: <https://opengis.net/def/function/geosparql/custom#>
prefix geosparql: <http://www.opengis.net/ont/geosparql#>

CONSTRUCT  {
    ?s geosparql:lineLength ?value
}
WHERE {
    ?s geosparql:asWKT ?wkt
    BIND (geoc:lineLength(?wkt) as ?value)
}