server:
  port : 8082
orchestrator:
  input:
    name: "be.vlaanderen.informatievlaanderen.ldes.ldto.input.LdtoHttpIn"
  transformers:
    - name: "be.vlaanderen.informatievlaanderen.ldes.ldto.transformer.SparqlConstructTransformer"
      config:
        query: "
            PREFIX core: <http://www.w3.org/2004/02/skos/core#>
            CONSTRUCT {
                ?s ?p ?o .
                ?s1 core:prefLabel ?label
            }
            WHERE {
                ?s ?p ?o .
                ?s1 core:prefLabel ?notes .
                BIND(CONCAT(STR( ?notes ), ' (Changed by construct transformer)')  AS ?label ) .
                MINUS {
                    ?s core:prefLabel ?x .
                }
            }
          "
  outputs:
    - name: "be.vlaanderen.informatievlaanderen.ldes.ldto.output.LdtoConsoleOut"
      config:
        content-type: "application/n-quads"
    - name: "be.vlaanderen.informatievlaanderen.ldes.ldto.output.LdtoGraphDbOut"
      config:
        databaseUrl: "http://graphdb:7200"
        repository: "GIPOD"
