name: 2.b Build LDIO Docker

on:
  workflow_run:
    workflows: [ 2.a Build Project ]
    types: [ completed ]
    conclusion: success
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: informatievlaanderen/ldi-orchestrator

jobs:
  build-docker-ldio:
    name: Build and push LDIO image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          # Temporary workaround for buildx problem
          # See: https://github.com/docker/build-push-action/issues/761#issuecomment-1383822381
          driver-opts: |
            image=moby/buildkit:v0.10.6
      - name: set release date
        run: |
          echo "BUILD_DATE=$(date +'%Y%m%dT%H%M%S')" >> ${GITHUB_ENV}
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ldio.Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest , ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_DATE }}
          platforms: linux/amd64,linux/arm64