name: 3. Approve Snapshot

on:
  push:
    branches:
      - ci/approve-snapshot
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ldi-orchestrator

jobs:
  approve-snapshot:
    #if: github.ref == "refs/heads/main"
    name: Approve Snapshot and Promote
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 18
      - name: Determine version
        run: |
          export VERSION=$(mvn help:evaluate -Dexpression="project.version" -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_ENV
      - name: Define docker variables
        run: |
          if [[ "${{ env.version }}" != *"SNAPSHOT"* ]]; then
            echo "Dealing with a snapshot version"
            echo "${{ env.version }}"
          fi
          else
            echo "Already released"
          fi