name: Add bugs to bugs project

on:
  issues:
    types:
      - opened

env:
  PROJECT_URL: ${{ vars.PROJECT_URL || 'https://github.com/orgs/Informatievlaanderen/projects/4' }}

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: ${{ env.PROJECT_URL }}
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}